//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ca()
        {
            this.prisustvujes = new HashSet<prisustvuje>();
        }
        [Key]    
        public int ID_Cas { get; set; }
        public System.DateTime Datum { get; set; }
        public int ProfesorID { get; set; }
        public int KursID { get; set; }
        [Required(ErrorMessage ="polje je obavezno")]
        public string Opis { get; set; }
    
        public virtual Kur Kur { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisustvuje> prisustvujes { get; set; }
    }
}
