//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ispit_Odrzavanje
    {
        public string Id_IspitOdrz { get; set; }
        public int IspitID_FK { get; set; }
        public int StudentID_FK { get; set; }
        public int Ocena { get; set; }
        public string Rad { get; set; }
    
        public virtual Ispit Ispit { get; set; }
        public virtual Student Student { get; set; }
    }
}
