//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        [Key]
        public int id_Login { get; set; }
        [Required(ErrorMessage ="polje je obavezno")]
        public string username { get; set; }
        [Required(ErrorMessage ="polje je obavezno")]
        [DataType(DataType.Password)]
        public string password { get; set; }
        public string userType { get; set; }
        public string LoginErrorMessage { get; set; }
        public Nullable<int> korisnikID_FK { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
