//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
   
    
    public partial class KontaktOsoba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KontaktOsoba()
        {
            this.ListaSkolas = new HashSet<ListaSkola>();
        }
    
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string RadnoMesto { get; set; }
        public int TelefonFK { get; set; }
        public int MailFK { get; set; }
    
        public virtual ListaMailAdresa ListaMailAdresa { get; set; }
        public virtual ListaTelefona ListaTelefona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListaSkola> ListaSkolas { get; set; }
    }
}
