//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ListaSkola
    {
        [Key]
        public int idS { get; set; }
       [Required(ErrorMessage ="Pogresno unet naziv skole!")]
       [DisplayName("Naziv skole")]
        public string NazivSkole { get; set; }
        [Required(ErrorMessage ="Pogresno uneta adresa skole!")]
        [DisplayName("Adresa registracije skole")]
        [RegularExpression("^[A-Za-z0-9 _]*[A-Za-z0-9][A-Za-z0-9 _]*$")]
        public string AdresaReg { get; set; }
        [Required(ErrorMessage ="Pogresno uneto ime opstine!")]
        [DisplayName("Opstina")]
        [RegularExpression("^[A-Za-z ]+$",ErrorMessage ="Pogresan format")]
        public string Opstina { get; set; }
        [Required(ErrorMessage ="Pogresno unet postanski broj!")]
        [DisplayName("Postanski broj")]
        [RegularExpression("^[0-9]*")]
        public int PostanskiBroj { get; set; }
        [Required(ErrorMessage ="Pogresno unet maticni broj!")]
        [DisplayName("Maticni broj")]
        [RegularExpression("^[0-9]*")]
        public int MaticniBroj { get; set; }
        [Required(ErrorMessage ="Pogresno unet PIB!")]
        [DisplayName("PIB")]
        [RegularExpression("^[0-9]*")]
        public string pib { get; set; }
        [Required(ErrorMessage = "Pogresno unet broj racuna!")]
        [DisplayName("Broj racuna")]
        [RegularExpression("^[0-9]*")]
        public string BrojRacuna { get; set; }
        [Required(ErrorMessage = "Pogresno uneta web stranica!")]
        [DisplayName("Web stranica")]
        [RegularExpression(@"(http(s)?://)?([\w-]+\.)+[\w-]+(/[\w- ;,./?%&=]*)?",ErrorMessage ="Pogresan format!")]
        public string WebStranica { get; set; }
        [DisplayName("Kontakt osoba")]
        public int KontaktOsobaFK { get; set; }
        [DisplayName("Link slike")]
        public string SlikaPecat { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string Beleske { get; set; }
    
        public virtual KontaktOsoba KontaktOsoba { get; set; }
    }
}
