//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class login
    {
        [Key]
        public int id { get; set; }
        [Required(ErrorMessage ="Ovo polje je obavezno!")]
        [DisplayName("Korisnicko ime")]
        public string username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage ="Ovo polje je obavezno!")]
        [DisplayName("Sifra")]
        public string password { get; set; }
        [Required(ErrorMessage ="Ovo polje je obavezno!")]
        [DisplayName("Tip korisnika")]
        public string userType { get; set; }
        public string SuccessAddUserAdmin { get; set; }
        public string SuccessAddUser { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
