//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projekatEntities : DbContext
    {
        public projekatEntities()
            : base("name=projekatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<KontaktOsoba> KontaktOsobas { get; set; }
        public virtual DbSet<ListaMailAdresa> ListaMailAdresas { get; set; }
        public virtual DbSet<ListaSkola> ListaSkolas { get; set; }
        public virtual DbSet<ListaTelefona> ListaTelefonas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
