//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Materijal
    {
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage ="polje je obavezno")]
        public string Ime { get; set; }
        public string Atribut { get; set; }
        public int ProfesorID { get; set; }
        public int KursID { get; set; }
    
        public virtual Kur Kur { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
