//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class prisustvuje
    {
        [Key]
        public int Id_Prisustvo { get; set; }
        public int CasID_FK { get; set; }
        public int StudentID_FK { get; set; }
        public Nullable<bool> prisutan { get; set; }
        public virtual Ca Ca { get; set; }
        public virtual Student Student { get; set; }
    }
}
