//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Ispit_Odrzavanje = new HashSet<Ispit_Odrzavanje>();
            this.prisustvujes = new HashSet<prisustvuje>();
            this.Transakcijas = new HashSet<Transakcija>();
        }
        [Key]
        public int StudentID { get; set; }
        public int Korisnik_FK { get; set; }
        public int Kurs_FK { get; set; }
        [Required(ErrorMessage ="vrednost od 0.0 do 5.0")]
        [Range(0.0,5.0)]
        public Nullable<double> ZakljucnaOcena { get; set; }
        public bool isChecked { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ispit_Odrzavanje> Ispit_Odrzavanje { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Kur Kur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisustvuje> prisustvujes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcija> Transakcijas { get; set; }
    }
}
