<?xml version="1.0" encoding="utf-8"?><Database Name="Apoteka" Class="ApotekaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-43MREHR;Initial Catalog=Apoteka;Integrated Security=True" SettingsObjectName="WpfApp2.Properties.Settings" SettingsPropertyName="ApotekaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Dijagnoza" Member="Dijagnozas">
    <Type Name="Dijagnoza">
      <Column Name="SifraBolesti" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Dijagnoza_Recept" Member="Recepts" ThisKey="SifraBolesti" OtherKey="SifraBolesti" Type="Recept" />
      <Association Name="Dijagnoza_Terapija" Member="Terapijas" ThisKey="SifraBolesti" OtherKey="SifraBolesti" Type="Terapija" />
    </Type>
  </Table>
  <Table Name="dbo.Recept" Member="Recepts">
    <Type Name="Recept">
      <Column Name="ReceptID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ime" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Prezime" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="BrKutija" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SifraBolesti" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SifraLeka" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Dijagnoza_Recept" Member="Dijagnoza" ThisKey="SifraBolesti" OtherKey="SifraBolesti" Type="Dijagnoza" IsForeignKey="true" />
      <Association Name="Terapija_Recept" Member="Terapija" ThisKey="SifraBolesti,SifraLeka" OtherKey="SifraBolesti,SifraLeka" Type="Terapija" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Terapija" Member="Terapijas">
    <Type Name="Terapija">
      <Column Name="SifraBolesti" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SifraLeka" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Doza" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Terapija_Recept" Member="Recepts" ThisKey="SifraBolesti,SifraLeka" OtherKey="SifraBolesti,SifraLeka" Type="Recept" />
      <Association Name="Dijagnoza_Terapija" Member="Dijagnoza" ThisKey="SifraBolesti" OtherKey="SifraBolesti" Type="Dijagnoza" IsForeignKey="true" />
    </Type>
  </Table>
</Database>