<?xml version="1.0" encoding="utf-8"?><Database Name="Katastar" Class="KatastarDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-43MREHR;Initial Catalog=Katastar;Integrated Security=True" SettingsObjectName="WpfApp3.Properties.Settings" SettingsPropertyName="KatastarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KatastarskeOpstine" Member="KatastarskeOpstines">
    <Type Name="KatastarskeOpstine">
      <Column Name="IDKatOpstina" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Naziv" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="KatastarskeOpstine_Objekti" Member="Objektis" ThisKey="IDKatOpstina" OtherKey="IDKatOpstina" Type="Objekti" />
    </Type>
  </Table>
  <Table Name="dbo.Objekti" Member="Objektis">
    <Type Name="Objekti">
      <Column Name="IDObjekta" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vlasnik" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Kvadratura" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Uknjizeno" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IDParcele" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDKatOpstina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KatastarskeOpstine_Objekti" Member="KatastarskeOpstine" ThisKey="IDKatOpstina" OtherKey="IDKatOpstina" Type="KatastarskeOpstine" IsForeignKey="true" />
      <Association Name="Parcele_Objekti" Member="Parcele" ThisKey="IDParcele,IDKatOpstina" OtherKey="IDParcele,IDKatOpstina" Type="Parcele" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parcele" Member="Parceles">
    <Type Name="Parcele">
      <Column Name="IDParcele" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDKatOpstina" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Povrsina" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Adresa" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Vlasnistvo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Parcele_Objekti" Member="Objektis" ThisKey="IDParcele,IDKatOpstina" OtherKey="IDParcele,IDKatOpstina" Type="Objekti" />
    </Type>
  </Table>
</Database>